### PR TITLE
feat: add new rule for checklist alt featured image

### PR DESCRIPTION
**Pull request by richaferry**
## Description

This PR want to solve this issue 
“All images have alt text” checklist item does not check the featured image #242
## Benefits

User can know if their post already had alt featured image or not using enable new rule from configuration page
## Checklist

- [x] I have created a specific branch for this pull request before committing, starting off the current HEAD of `development` branch. 
- [x] I'm submitting to the `development`, feature/hotfix/release branch. (Do not submit to the master branch!)
- [x] This pull request relates to a specific problem (bug or improvement).
- [x] I have mentioned the issue number in the pull request description text.
- [x] All the issues mentioned in this pull request relate to the problem I'm trying to solve.
- [x] The code I'm sending follows the [PSR-12](https://www.php-fig.org/psr/psr-12/) coding style.

### CODE REVIEW

**Review by olatechpro — CHANGES_REQUESTED** [review]
That looks good @richaferry 
However, there's something I noticed that needed a fix.
When i create new post, I still see "Alt text for featured images *" even though i didn't select any featured image.

**Review by olatechpro — CHANGES_REQUESTED** [review]
Also, this function is totally unneeded. JavaScript validation is done on at client side and no need of including `'featured_image_alt' => $this->featured_image_alt()`,  in the localize scripts

**Comment by richaferry** [comment]
Yes. Sure. Thankyou for your comment @olatechpro ,
So want to clarify. If new post and users didn't select any featured image which is flag
`Featured image` will be required but Alt text for featured images will be checked?
Also for `'featured_image_alt' => $this->featured_image_alt()` i think still needed. why? Because currently in gutenberg editor not passing alt text for featured image in sidebar. so still need store alt text from previous image. im prevent ajax request just for get alt image. and if user change featured image multiple times without autosave will be got previous values. so still need revalidate after user changes featured image from A tobe B.

**Comment by olatechpro** [comment]
Hi @richaferry 
1. Let me explain it this way, we have a requirement that says "Alt text for all images (Required)". That's same way as reading it as no image should exist without alt texts in the content. So, when no image is added to the content, that shows it's still a pass because we couldn't find any image that doesn't have alt text in the content. 

Same thing applied here, checking featured image alt requirement only matter when featured image is uploaded, it's automatically a pass if no featured image is uploaded because this requirement is not about featured image requirement but feature image alt and there's need to be featured image first before we can mark it as fail for lacking alt text.

2. If you need to do something in gutenberg editor, do it using provided function. Please refer to existing requirements to understand the code structure and how we're handling server and client side validation. 

To validate my point on the localize data not been needed, kindly replace `'featured_image_alt' => $this->featured_image_alt(),` with `featured_image_alt' => []`, and you'll see it changes nothing. That's because initial validation is done using the [get_current_status()](https://github.com/publishpress/PublishPress-Checklists/pull/573/files#diff-3d6b47bc8c6ed07ae4bcd21b1fea9be79d773e5bedf18eda2cb154702914b2b5R48) method in your class.

Let me know if you have any other question.

**Comment by richaferry** [comment]
Ok. Thank you @olatechpro for your explanation. Will trying to analyze first.

**Comment by olatechpro** [comment]
That's fine @richaferry Let me know if you need help or direction on this.

For my second issue, asking you to change the data to featured_image_alt' => [] is a way to proof it's not needed and the only thing needed to be done is removing it.

Regards.

**Comment by richaferry** [comment]
Hi @olatechpro ,
This is why we are still needed bridge data from php into js. 
https://github.com/publishpress/PublishPress-Checklists/assets/49858604/49a707a2-a41a-4687-82be-e5ab4e6fd7dd
Also i think we are can't used alt value from dom feature image. because currently not set properly in this editor
Screenshot 2024-01-14 at 00 05 44
So my solution is to pretend current alt value into javascript validation. But after reading some code and learning the flow i found new solution. My new solution can see in this commit ef7d6334bf7767dac7a208d3220b9bfc05053cbc

**Comment by richaferry** [comment]
If you want try version with set `featured_image_alt' => []` you can use this [link](https://app.instawp.io/wordpress-auto-login?site=%242y%2410%24p24snNyk.LVvsc%2Fn%2FzvC3Oq6npj1gKBqdu0nF5yJMvrw8VlLc2kTS)
If you want try new version you can use this [link](https://app.instawp.io/wordpress-auto-login?site=$2y$10$Pfyt7I6i.TizE0O8gk.NI.j1h.BWb1RomzZKYBiW4.i0RSE6uM0L.)

**Comment by richaferry** [comment]
Need your advice @olatechpro with my new commit. 
Thanks in advance

**Comment by olatechpro** [comment]
Hi @richaferry 
Sorry you end up going through that extra check. I think you could have gotten back to me on how to get featured image data which include alt text in Gutenberg editor since I told you it's possible. I only feel it's okay to let you try checking either the documentation or core code.  That's what I mean when I said you should let me know if you need help.

There's no reason to stress you if it's not posssible.

Also, choosing to read html dom attribute won't even be the best solution working with Gutenberg editor which is a react component unless there's no alternative but there is in this case.

So, here's the thing, we should only do things some ways only if it's not possible doing it the standard way.

So, here's the code you need to get featured image data including alt texts in Gutenberg editor:
`var featuredImageData = wp.data.select('core').getMedia(featuredImageId)`
With that, you'll be able to get featured image alt texts without passing data from PHP to JavaScript.

With that function, I believe you can remove the php to javascript code.

If you have question on this or it's not working for you for some reason, you should let me know but it works fine in my testing now.

Regards.

**Review by olatechpro — APPROVED** [review]
Good job @richaferry

**Pull request merged**
