### PR TITLE
Feature 270 status filter move to pro

### PR DESCRIPTION
**Pull request by julianactrl**
Hi @andergmartins ,
Please check this push.

### CODE REVIEW

**Comment by julianactrl** [comment]
Hello @stevejburge  and @andergmartins ,
Did you receive the pull request?

**Review by andergmartins — CHANGES_REQUESTED** [review]
Hi @julianactrl sorry for the delay to review the code.

I was checking and I got multiple page refreshes after saving the post.
Sorry, I don't think that refreshing the page is the right direction to go. Gutenberg is an async editor, we shouldn't force page refreshing.

The trigger when the post is saved is correct but I would suggest developing an Ajax request that would reload only the checklists metabox.

**Comment by julianactrl** [comment]
Hello @andergmartins and @stevejburge 

I just pushed new changes for updating metabox only when save post.

Please check it and let me know.

Thanks.

Juliana.

**Comment by andergmartins** [comment]
Hi @julianactrl sorry, I don't see the new changes you mention in the last message. Please, could you double-check if you pushed it to the correct branch?

**Comment by julianactrl** [comment]
> Hi @julianactrl sorry, I don't see the new changes you mention in the last message. Please, could you double-check if you pushed it to the correct branch?

https://github.com/publishpress/PublishPress-Checklists/pull/280/commits/8f654fc457a4bad90939c240afcf8ea186c21c0b
https://github.com/publishpress/PublishPress-Checklists/pull/280/commits/d0da155c54ec96c566a515be6ba8ebb962a409ee

Can't you see these commits?

**Comment by andergmartins** [comment]
Sorry, my bad @julianactrl . Yes, I can see them, thank you. I will finish the review in the morning.

**Comment by julianactrl** [comment]
Okay, Thanks.

**Review by andergmartins — CHANGES_REQUESTED** [review]
Hi @julianactrl 

Thanks! It is a lot better, almost there. Sorry, but I still see an issue.
Please, check the following screenshots:

The settings on my test:
Screen Shot 2021-05-25 at 14 11 29

The post edit page, with the checklists working good, initially:

Screen Shot 2021-05-25 at 14 11 48

Then I try to click on Save as Draft. There is an error message and the checklist item becomes unchecked:

Screen Shot 2021-05-25 at 14 12 52

Then I publish the post. The other checklist correctly appears, but both are still unchecked.

Screen Shot 2021-05-25 at 14 13 41

**Comment by julianactrl** [comment]
Hello @andergmartins ,

Please check new commits again.

Commit url is 
https://github.com/publishpress/PublishPress-Checklists/pull/280/commits/26c5fb1495482e94d37b0f79cd13b97eec76ff7e

and (resolve conflicting)
https://github.com/publishpress/PublishPress-Checklists/pull/280/commits/da8a6eeb50e488dba6b02195a3ce9c89c4aefc86

**Comment by andergmartins** [comment]
Thanks @julianactrl! That fixed the bug. And thanks for the fix on the event listeners, that does make sense.
In a final testing I found that custom requirements can't be checked if using your branch. Please, could you do a quick check?

Screen Shot 2021-05-28 at 17 47 20

I see this on Query Monitor debug output after I click on the custom checkbox:

image

**Comment by julianactrl** [comment]
Hi @stevejburge  and @andergmartins,
I fixed custom box click event issue.
Please check it.
And I will send you and email @stevejburge .
Thanks.

**Review by andergmartins — APPROVED** [review]
Thanks @julianactrl! It looks great

**Comment by julianactrl** [comment]
Hi,

How can I contact with @stevejburge ?

**Comment by julianactrl** [comment]
Hello Steve,
Sorry for bothering you.
Would you like to check your mail?
I think you missed my email, please check my email and let me know.
Thanks.

**Pull request merged**
